#!/bin/bash
# example:
# $ replace-text.sh ./ text-to-replace replacement-text

# find and replace strings in files with sed regex
# avoid directories

grep -rl --exclude-dir="*.git" "$2" "$1" | xargs sed -i s^"$2"^"$3"^g

